### ISSUE TITLE
pciread output can't be redirected in epics shell

### ISSUE THREAD

**Issue by krmpotic** [epics-modules/devlib2#12]
When I try to do:
epics> pciread 32 0x0 32 > /tmp/file

There is nothing in the file, and output is still displayed at ioc shell.

Redirection would be a useful feature for doing bigger register dumps

**Comment by dirk-zimoch** [comment]
Looks like `#include "epicsStdioRedirect.h"` is missing.

**Comment by mdavidsaver** [comment]
Should be corrected with 1713cce65cf98f8c7a1482fb3b29d3a03384c398.  Most of the changes are the ensure that error messages are not redirected by stdout.

> Looks like `#include "epicsStdioRedirect.h"` is missing.

```c
/* epicsStdioRedirect.h */

/* This file is now obselete, and is likely to be
 * deleted in a future release of EPICS Base.
 *
 * Use the epicsStdio.h header file instead.
 */
```

**Comment by krmpotic** [comment]
I tested it and it works with 5d28689a9.
That was fast!

**Comment by dirk-zimoch** [comment]
Depending on your EPICS base version you may still need epicsStdioRedirect. Test with R3.14.12 please.

**Comment by dirk-zimoch** [comment]
Redirection does not work with 3.14.12.

**Comment by dirk-zimoch** [comment]
A change like this could solve the problem with redirection in 3.14.12 and with epicsStdioRedirect.h being obsolete in 3.15+

```
+#include <epicsVersion.h>
+#ifndef EPICS_VERSION_INT
+#include <epicsStdioRedirect.h>
+#endif
```

**Comment by jerzyjamroz** [comment]
Hi, is it still valid? Or can I close it?

**Comment by krmpotic** [comment]
I am not working on this anymore. Looks OK to close for me.
