### ISSUE TITLE
Problems with vxWorks 5

### ISSUE THREAD

**Issue by dirk-zimoch** [epics-modules/devlib2#3]
There are some minor compilation problems
- vxWorks 5 has no strdup()
- The PCIUINT32 type did not match the vxWorks pciConfigInLong() argument
- Some // comments in C code cause warnings with -ansi flag

[Patch](https://github.com/epics-modules/devlib2/files/458960/vxWorks5fixes.patch.txt) attached.

**Comment by mdavidsaver** [comment]
Applied as 5cf3c40dc72c070b551cb3c15bea65ec3d15e4d8 and 8a284e834c743f4ea7a75de7e27fa4f651feae2f

I need to find some tool which checks for c++ style comments in c code...
