### ISSUE TITLE
Does not compile on Windows

### ISSUE THREAD

**Issue by dirk-zimoch** [epics-modules/devlib2#9]
I am working on a merge reqest with come of the changes we did as PSI to make the code Windows compatible.

**Comment by mdavidsaver** [comment]
Yay!  Let me know if you see trouble with the appveyor build (which should be setup for this repo).

**Comment by mdavidsaver** [comment]
The appveyor build now succeeds!  https://ci.appveyor.com/project/mdavidsaver/devlib2/builds/34871333
